routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| Indice de Rutas
|--------------------------------------------------------------------------
|
| Raiz (/)
| Auth Routes
| Home
| Rutas de Recursos
| Rutas Champions Tools
| Rutas Ajax
|
*/

Route::get('/', function () {
	//return view('welcome');
	return redirect()->route('home');
});

Route::get('/vw_info_php', function(){
return view('info');
});




Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware(['auth','verified','web']);
Route::get('/sitio/en/construccion', 'HomeController@en_construccion')->name('web.en.construccion')->middleware(['auth','verified','web']);

Route::resource('roles', 'RoleController')->middleware(['auth','verified','web']);
Route::get('/roles/permisos/{id_role}','RoleController@permisos')
            ->name('roles.permisos')
            ->middleware(['auth','verified','web']);

Route::post('/roles/asignar/permiso','RoleController@AsociarPermiso')
            ->name('roles.asignar.permiso')
            ->middleware(['auth','verified','web']);

Route::get('permitir','RoleController@permitir')->name('permitir');
Route::resource('permisos', 'PermissionController')->middleware(['auth','verified','web']);
Route::resource('paises', 'CountryController')->middleware(['auth','verified','web']);

Route::resource('empleados', 'EmployeeController')->middleware(['auth','verified','web']);
Route::post('/empleados/filtros','EmployeeController@filtros')
			->name('empleados.filtros')
			->middleware(['auth','verified','web']);

Route::resource('lideres', 'HeadController')->middleware(['auth','verified','web']);
Route::resource('cargos', 'PositionController')->middleware(['auth','verified','web']);
Route::resource('usuarios', 'UserController')->middleware(['auth','verified','web']);
Route::resource('canales', 'ChannelController')->middleware(['auth','verified','web']);
Route::resource('territorios', 'TerritoryController')->middleware(['auth','verified','web']);
Route::resource('regionales', 'RegionalController')->middleware(['auth','verified','web']);

Route::resource('admins', 'AdminsController')->middleware(['auth','verified','web']);

Route::post('/admins/buscar','AdminsController@buscar_empleado')
			->name('admins.buscar.empleado')
			->middleware(['auth','verified','web']);

Route::get('/admins/ver/buscar','AdminsController@ver_buscar_empleado')
			->name('admins.ver.buscar.empleado')
            ->middleware(['auth','verified','web']);

Route::resource('logs', 'LogController')->middleware(['auth','verified','web']);

Route::get('logs/export/accesos/{rango}/{cedula}', 'LogController@exportar_accesos')
            ->name('log.exportar.accesos')
            ->middleware(['auth','verified','web']);

Route::get('logs/export/accesos/resumen/{rango}/{cedula}', 'LogController@exportar_accesos_resumen')
            ->name('log.exportar.accesos.resumen')
            ->middleware(['auth','verified','web']);

Route::post('/logs/traer_cedula','LogController@traer_cedula')
            ->name('log.traer.cedula')
            ->middleware(['auth','verified','web']);

Route::post('/visits/register','VisitsController@registrar_visita')
            ->name('visits.register')
            ->middleware(['auth','verified','web']);

Route::post('/visits/close','VisitsController@cerrar_visita')
            ->name('visits.close')
            ->middleware(['auth','verified','web']);


//ENCUESTAS
// =============================================================================================
Route::get('encuestas/formularios/{visita}/{form}', 'EncuestasController@formularios_encuestas')
            ->name('encuestas.formularios')
            ->middleware(['auth','verified','web']);

Route::get('encuestas/oficiales/{id_encuesta}/{version}/{idpdv}/{doc_acomp?}','EncuestasController@encuestas_oficiales')
            ->name('encuestas.oficiales')
            ->middleware(['auth','verified','web']);

Route::get('encuestas/preguntas/constructor/{encuesta_visita}/{encuesta}/{version}/{completada}/{pregunta}/{anterior}/{doc_acomp?}/{atras?}/{id_opc_resp?}/{txt_opc_resp?}/{txt_resp?}/{calif_resp?}','EncuestasController@encuestasPreguntasConstructor')
            ->name('encuestas.preguntas.constructor')
            ->middleware(['auth','verified','web']);


Route::post('encuestas/guardar','EncuestasController@encuestas_guardar')
            ->name('encuestas.validar.guardar')
            ->middleware(['auth','verified','web']);

Route::post('encuestas/regresar','EncuestasController@encuestas_regresar')
            ->name('encuestas.pregunta.anterior')
            ->middleware(['auth','verified','web']);

Route::get('/checklist/ver/salida','EncuestasController@ver_check_ruta')
			->name('encuestas.ver.check.salida')->middleware(['auth','verified','web']);

Route::post('/checklist/crear/salida','EncuestasController@crear_check_ruta')
			->name('encuestas.crear.check.salida')->middleware(['auth','verified','web']);

Route::get('/coaching/ver','EncuestasController@ver_coachings')
			->name('encuestas.ver.coachings')->middleware(['auth','verified','web']);

Route::get('/coaching/finalizar/{id}','EncuestasController@finalizar_coachings')
            ->name('encuestas.finalizar.coachings')->middleware(['auth','verified','web']);

Route::get('/tracking/ver/salida','EncuestasController@iniciar_tracking')
            ->name('encuestas.iniciar.tracking')->middleware(['auth','verified','web']);

Route::post('/tracking/crear','EncuestasController@crear_tracking_competencia')
			->name('encuestas.crear.tracking.competencia')->middleware(['auth','verified','web']);

// =============================================================================================

//RUTAS CHAMPIONS TOOLS
Route::get('/dash_pospago', function () {
	return view('bi.ctools.dash_movil');
})->name('bi.ctools.movil')
  ->middleware(['auth','verified','web']);

Route::get('/dash_home', function () {
	return view('bi.ctools.dash_home');
})->name('bi.ctools.home')
  ->middleware(['auth','verified','web']);

// *******************************************************************************************
// *******************************************************************************************
//RUTAS PARA GESTION EN PUNTO DE VENTA
Route::group(['prefix' => 'gestion'], function () {

    Route::get('/buscar_punto','GestionController@buscarPunto')->name('gestion.buscar.punto')->middleware(['auth','verified','web']);
    Route::post('/buscar_punto','GestionController@traerPunto')->name('gestion.traer.punto')->middleware(['auth','verified','web']);
    Route::post('/buscar_nom_punto','GestionController@traerNombrePunto')->name('gestion.traer.nombre.puntos')->middleware(['auth','verified','web']);
    Route::post('/buscar_cc_owner','GestionController@traerCedulaPropietario')->name('gestion.traer.cedula.propietario')->middleware(['auth','verified','web']);
	Route::post('/buscar_pos_code','GestionController@traerCodigoPos')->name('gestion.traer.pos.code')->middleware(['auth','verified','web']);
    Route::post('/buscar_circuito_estado','GestionController@traerCircuitoEstado')->name('gestion.traer.circuito.estado')->middleware(['auth','verified','web']);
    Route::post('/buscar_puntos_ruta_dia','GestionController@traerPuntosRutaDia')->name('gestion.puntos.ruta.dia')->middleware(['auth','verified','web']);
    Route::post('/confidencialidad','GestionController@confidencialidad')->name('gestion.guardar.confidencialidad')->middleware(['auth','verified','web']);
    Route::post('/gestion_fotos','GestionController@foto_punto_venta')->name('gestion.cargar.foto')->middleware(['auth','verified','web']);

	Route::post('/gestion_correos','GestionController@email_pv')->name('gestion.correo.pv')->middleware(['auth','verified','web']);

});

// *******************************************************************************************

// -------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------
//RUTAS PARA PLANEACION
Route::group(['prefix' => 'planeacion'], function () {
    Route::get('/ver_planeador','PlaneadorController@verPlaneador')->name('planeacion.ver.planeador')->middleware(['auth','verified','web']);
});
// *******************************************************************************************

//RUTAS PARA REPORTE DE TIENDAS
Route::group(['prefix' => 'tiendas'], function () {
	Route::get('/ns/ver/{aliado?}/{regional?}','ReporteTiendasController@ver_ns')->name('tiendas.ver.ns')->middleware(['auth','verified','web']);
	Route::get('/nps/ver/{canal?}/{negocio?}/{regional?}/{tienda?}','ReporteTiendasController@ver_nps')->name('tiendas.ver.nps')->middleware(['auth','verified','web']);
});


//RUTAS PARA SEGUIMIENTO RETAIL
Route::group(['prefix' => 'retail'], function () {
	Route::get('/ver_todo','RetailController@ver_todo')->name('retail.ver.todo')->middleware(['auth','verified','web']);
	Route::get('/ver_regional/{regional}','RetailController@ver_regional')->name('retail.ver.regional')->middleware(['auth','verified','web']);
	Route::get('/ver_regional/{regional}/{departamento}','RetailController@ver_departamento')->name('retail.ver.departamento')->middleware(['auth','verified','web']);

	Route::get('/export/nacional', 'RetailController@exportar_puntos_nacional')->name('retail.exportar.nacional')->middleware(['auth','verified','web']);

resources/views/admins/buscar_empleado.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Buscar Empleado</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('admins.index') }}"> Regresar</a>
    </div>
  </div>
</div>


<form action="{{ route('admins.buscar.empleado') }}" method="POST">
  @csrf

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Ingrese Cedula Empleado:</strong>
        <input type="text" id="cedula_empleado" name="cedula_empleado" value="{{ old('cedula_empleado') }}" class="form-control @error('cedula_empleado') is-invalid @enderror" placeholder="Ingrese cedula">
        @error('cedula_empleado')
        <span class="invalid-feedback" role="alert">
          <strong>{{ $message }}</strong>
        </span>
        @enderror
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-sm btn-primary">Buscar</button>
    </div>
  </div>

</form>

@endsection

resources/views/admins/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Asignar Administrador</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('admins.index') }}"> Regresar</a>
    </div>
  </div>
</div>
@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> Hubo algunos problemas con su Informacion.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif
<hr>
<form action="{{ route('admins.store') }}" method="POST">
  @csrf
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Nombre:</strong>
        {{ $administrador['nom_empleado'] }}
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Cargo:</strong>
        {{ $administrador['nom_cargo'] }}
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Regional:</strong>
        {{ $administrador['nom_regional'] }}
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Canal:</strong>
        {{ $administrador['nom_canal'] }}
      </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Asignar a Regional:</strong>
        <select id="regional_asignada" name="regional_asignada" class="form-control">
          @foreach($regionales as $regional)
            <option value="{{ $regional['id'] }}" {{ ($regional['id'] == $administrador['id_regional']) ? 'selected':'' }}>
              {{ $regional['regional_name'] }}
            </option>
          @endforeach
        </select>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Asignar a Canal:</strong>
        <select id="canal_asignado" name="canal_asignado" class="form-control">
          @foreach($canales as $canal)
            <option value="{{ $canal['id'] }}" {{ ($canal['id'] == $administrador['id_canal']) ? 'selected':'' }}>
              {{ $canal['channel_name'] }}
            </option>
          @endforeach
        </select>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Admin / CoAdmin:</strong>
        <select id="nivel_asignado" name="nivel_asignado" class="form-control">
          <option value="X" selected>- Seleccione Por Favor -</option>
          <option value="ADMIN">Administrador Regional</option>
          <option value="COADMIN">CoAdministrador Regional</option>
        </select>
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-sm btn-primary">Crear</button>
    </div>

    <input type="hidden" name="empleado_asignado" value="{{ $administrador['id_empleado'] }}">
    <input type="hidden" name="usuario_asignado" value="{{ $administrador['id_usuario'] }}">
    <input type="hidden" name="cedula_empleado" value="{{ $administrador['cedula_empleado'] }}"><br />

  </div>
</form>

@endsection

resources/views/admins/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Editar Role</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('roles.index') }}"> Regresar</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> Parece que tenemos algun problema con su Actualizacion.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

<form action="{{ route('roles.update',$role->id) }}" method="POST">
  @csrf
  @method('PUT')

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Nombre Role:</strong>
        <input type="text" name="name" value="{{ $role->name }}" class="form-control" placeholder="Nombre Role">
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
  </div>

</form>

@endsection

resources/views/admins/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Administradores Regionales</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-success" href="{{ route('admins.ver.buscar.empleado') }}">
        <i class="fas fa-plus-circle"></i> Nuevo Administrador
      </a>
      <a class="btn btn-sm btn-info" href="{{ route('empleados.index') }}">
        <i class="far fa-user-circle"></i> Ver Empleados
      </a>
    </div>
  </div>
</div>

@if ($message = Session::get('success'))
  @include('layouts.alert_success')
@endif
@if ($message = Session::get('error'))
  @include('layouts.alert_error')
@endif

<table class="table table-bordered">
  <tr>
    <th>Empleado</th>
    <th>Cedula</th>
    <th>Regional Asociada</th>
    <th>Canal Asociado</th>
    <th>Admin/CoAdmin</th>
    <th>Acciones</th>
  </tr>
  @foreach ($administradores as $admin)
  <tr>
    <td>{{ $admin->user->name }}</td>
    <td>{{ $admin->employee->document }}</td>
    <td>{{ $admin->regional->regional_name }}</td>
    <td>{{ $admin->channel->channel_name }}</td>
    <td>{{ $admin->level }}</td>
    <td>

      <form action="{{ route('admins.destroy',$admin->id) }}" method="POST">

        @csrf
        @method('DELETE')
        <a class="btn btn-sm btn-info" href="{{ route('admins.show',$admin->id) }}">
          <i class="fas fa-search"></i></a>
        <!--
                    <a class="btn btn-sm btn-primary" href="{ route('roles.edit',$admin->id) }"><i class="fas fa-edit"></i></a>
                    -->
        <button type="submit" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i></button>
      </form>
    </td>
  </tr>
  @endforeach
</table>

{!! $administradores->links() !!}

@endsection

resources/views/admins/show.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2> Ver Role</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('admins.index') }}"> Regresar</a>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Nombre:</strong>
      {{ $administrador->user->name }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Cargo:</strong>
      {{ $administrador->employee->position->position_name }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Regional Asociada:</strong>
      {{ $administrador->regional->regional_name }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Canal Asociado:</strong>
      {{ $administrador->channel->channel_name }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Admin/CoAdmin:</strong>
      {{ $administrador->level }}
    </div>
  </div>
</div>

@endsection