routes/web.php
Route::group(['prefix' => 'planeacion'], function () {
    Route::get('/ver_planeador','PlaneadorController@verPlaneador')->name('planeacion.ver.planeador')->middleware(['auth','verified','web']);
});
// *******************************************************************************************

//RUTAS PARA REPORTE DE TIENDAS
Route::group(['prefix' => 'tiendas'], function () {
	Route::get('/ns/ver/{aliado?}/{regional?}','ReporteTiendasController@ver_ns')->name('tiendas.ver.ns')->middleware(['auth','verified','web']);
	Route::get('/nps/ver/{canal?}/{negocio?}/{regional?}/{tienda?}','ReporteTiendasController@ver_nps')->name('tiendas.ver.nps')->middleware(['auth','verified','web']);
});


//RUTAS PARA SEGUIMIENTO RETAIL
Route::group(['prefix' => 'retail'], function () {
	Route::get('/ver_todo','RetailController@ver_todo')->name('retail.ver.todo')->middleware(['auth','verified','web']);
	Route::get('/ver_regional/{regional}','RetailController@ver_regional')->name('retail.ver.regional')->middleware(['auth','verified','web']);
	Route::get('/ver_regional/{regional}/{departamento}','RetailController@ver_departamento')->name('retail.ver.departamento')->middleware(['auth','verified','web']);

	Route::get('/export/nacional', 'RetailController@exportar_puntos_nacional')->name('retail.exportar.nacional')->middleware(['auth','verified','web']);
	Route::get('/export/regional/{regional}', 'RetailController@exportar_puntos_regional')->name('retail.exportar.regional')->middleware(['auth','verified','web']);
	Route::get('/export/departamento/{regional}/{departamento}', 'RetailController@exportar_puntos_departamento')->name('retail.exportar.departamento')->middleware(['auth','verified','web']);
});

//RUTAS PARA MAPA DE GESTORES
Route::group(['prefix' => 'mapas'], function () {
    Route::get('/georeferenciar','MapaGestorController@entrar')->name('mapas.gestores.entrar');
    Route::post('/validar_gestores','MapaGestorController@validar')->name('mapas.gestores.validar');//->middleware(['auth','verified','web']);

//RUTAS PARA MAPA MOC (mapa oportunidades comerciales)
    Route::post('/ver_cve','MapaGestorController@ver_cve')->name('mapas.ver.cve')->middleware(['auth','verified','web']);
    Route::get('/ver_opciones','MapaGestorController@verOpciones')->name('mapas.ver.opciones.moc')->middleware(['auth','verified','web']);

//RUTAS PARA MAPA CENSO (mapa censo puntos propios)
	Route::get('/ver_censo/{c_cves}/{c_antenas}/{c_cciales}/{c_puntos}','MapaGestorController@verCenso')->name('mapas.ver.censo.propios')->middleware(['auth','verified','web']);
	Route::post('/actualizar_censo','MapaGestorController@ActualizarCenso')->name('mapas.actualizar.censo.propios')->middleware(['auth','verified','web']);

//RUTAS PARA MAPA CENSO BOC (mapa censo BOC Bolivia)
	Route::get('/ver_censo_boc/{c_cves}/{c_circuitos}/{c_puntos}','MapaGestorController@verCensoBOC')->name('mapas.ver.censo.boc')->middleware(['auth','verified','web']);
	Route::post('/actualizar_censo_boc','MapaGestorController@ActualizarCensoBOC')->name('mapas.actualizar.censo.boc')->middleware(['auth','verified','web']);


//PARA EXPORTAR UN EXCEL DE LOS PUNTOS DEL CVE
    Route::get('/export/puntos/{cve}', 'MapaGestorController@exportar_puntos_cve')
            ->name('mapas.exportar.puntos')->middleware(['auth','verified','web']);
});

//RUTAS PARA TRADE MARKETING
Route::group(['prefix' => 'trade'], function () {
    /*
        GET /trade/Path             index()     tradePathController@index   name('trade.path.index')
        GET /trade/Path/create      create()    tradePathController@create  name('trade.path.create')
        POST /trade/Path            store()     tradePathController@store   name('trade.path.store')
        GET /trade/Path/{id}        show()      tradePathController@show    name('trade.path.show')
        GET /trade/Path/{id}/edit   edit()      tradePathController@edit    name('trade.path.edit')
        PUT/PATCH /trade/Path/{id}  update()    tradePathController@update  name('trade.path.update')
        DELETE /trade/Path/{id}     destroy()   tradePathController@destroy name('trade.path.destroy')
    */
    Route::get('/seleccionar_implementacion','TradePiezasController@seleccionaImplementacion')->name('trade.selecciona.implementacion')->middleware(['auth','verified','web']);
    Route::post('/implementacion_seleccionada','TradePiezasController@implementacionSeleccionada')->name('trade.implementacion.seleccionada')->middleware(['auth','verified','web']);
	Route::get('/asociar_piezas/{impl}/{pieza}','TradePiezasController@asociarPiezas')->name('trade.piezas.asociado')->middleware(['auth','verified','web']);
	Route::get('/desasociar_piezas/{impl}/{pieza}','TradePiezasController@desasociarPiezas')->name('trade.piezas.desasociado')->middleware(['auth','verified','web']);

	Route::post('/implementacion_auditada','TradePiezasController@implementacionAuditada')->name('trade.implementacion.auditada')->middleware(['auth','verified','web']);
	Route::get('/ver_auditorias/{impl}/{idpdv}','TradePiezasController@verAuditoria')->name('trade.implementacion.ver.auditorias')->middleware(['auth','verified','web']);

	Route::get('/implementacion/reactivar/{id}','TradeImplementacionController@reactivate')->name('trade.implementacion.reactivar')->middleware(['auth','verified','web']);

	Route::post('/colocacion_seleccionada','TradePiezasController@ColocacionSeleccionada')->name('trade.colocacion.seleccionada')->middleware(['auth','verified','web']);
	Route::get('/colocar_piezas/{idpdv}/{impl}/{pieza}','TradePiezasController@colocarPiezas')->name('trade.piezas.colocar')->middleware(['auth','verified','web']);
    Route::get('/quitar_piezas/{idpdv}/{impl}/{pieza}','TradePiezasController@quitarPiezas')->name('trade.piezas.quitar')->middleware(['auth','verified','web']);

    Route::get('/inventario/ver/{impl_pieza}','TradePiezasController@verInventario')->name('trade.inventario.ver')->middleware(['auth','verified','web']);
    Route::post('/inventario/ajustar/inventario','TradePiezasController@ajustarInventario')->name('trade.inventario.ajustar')->middleware(['auth','verified','web']);

    Route::get('/dash/ver','TradePiezasController@dashVer')->name('trade.dash.ver')->middleware(['auth','verified','web']);
    Route::get('/dash/ver/implementacion/{implementacion}','TradePiezasController@dashVerImplementacion')->name('trade.dash.ver.implementacion')->middleware(['auth','verified','web']);
	Route::get('/dash/ver/regional/{implementacion}/{regional}','TradePiezasController@dashVerRegional')->name('trade.dash.ver.regional')->middleware(['auth','verified','web']);

    //Reporte de Excel
    Route::get('implementacion/export', 'TradePiezasController@exportar_reporte_basico')->name('trade.exportar.reporte.basico')->middleware(['auth','verified','web']);
    //Resource
    Route::resource('clases', 'TradeClaseController')->middleware(['auth','verified','web']);
    Route::resource('contenidos', 'TradeContenidoController')->middleware(['auth','verified','web']);
    Route::resource('objetivos', 'TradeObjetivoController')->middleware(['auth','verified','web']);
    Route::resource('implementaciones', 'TradeImplementacionController')->middleware(['auth','verified','web']);
    Route::resource('tipos', 'TradeTipoController')->middleware(['auth','verified','web']);
    Route::resource('piezas', 'TradePiezasController')->middleware(['auth','verified','web']);
    Route::resource('clasehallazgo', 'TradeClaseHallazgoController')->middleware(['auth','verified','web']);
    Route::resource('hallazgos', 'TradeHallazgosController')->middleware(['auth','verified','web']);
    /*
    Route::get('/ver_piezas','TradePiezas@verPiezas')->name('trade.piezas.ver')->middleware(['auth','verified','web']);
    */
});

/***************************************************************************************************
*** PRUEBA PARA GEOCODER EN INFOPOS
***************************************************************************************************/
Route::get('/cercanos',function(){
    return view('cercanos.ver');
})->name('cercanos.ver')->middleware(['auth','verified','web']);
//********************************************************************************************** */


/***************************************************************************************************
*** PRUEBA PARA ADMINISTRACION DE ARCHIVOS EN INFOPOS
***************************************************************************************************/
Route::get('/verArchivos','ArchivosController@verArchivos')->name('archivos.verArchivos')
                                                           ->middleware(['auth','verified','web']);

Route::get('/{archivo}','ArchivosController@descargarArchivos')->name('archivos.descargarArchivos')
                                                           ->middleware(['auth','verified','web']);

//********************************************************************************************** */


//  Route::view('error', 'error', ['error' => $error])->name('error');

/*
|--------------------------------------------------------------------------
| Rutas Ajax
|--------------------------------------------------------------------------
|
| Nos van a ayudar a generar iteraccion con ajax
| queda pendiente evaluar reemplazar con VUE JS
| de momento queda este parche
|
*/

Route::get( '/ajax/pais/{id}',
			'JqueryController@ajaxPaisRegiones')->name('ajax.pais.regiones')
												->middleware(['web']);      //->middleware(['auth','verified','web'])

Route::get( '/ajax/region/{id}',
			'JqueryController@ajaxRegionTerritorios')->name('ajax.region.territorios')
												     ->middleware(['web']);  //->middleware(['auth','verified','web'])

Route::get( '/ajax/empleado/{cedula}',
			'JqueryController@ajaxCedulaEmpleado')->name('ajax.cedula.empleado')
												     ->middleware(['web']);  //->middleware(['auth','verified','web'])


Route::get( '/ajax/circuito/autocompletar',

resources/views/trade/clasehallazgo/create.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Crear Nueva Clase de Hallazgo</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('clasehallazgo.index') }}"> Regresar</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> Hubo algunos problemas con su entrada.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

<form action="{{ route('clasehallazgo.store') }}" method="POST">
  @csrf

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Nombre Nueva Clase:</strong>
        <input type="text" name="nombre_clase" class="form-control" placeholder="Ingrese Nombre">
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-sm btn-primary">Crear</button>
    </div>
  </div>

</form>

@endsection

resources/views/trade/clasehallazgo/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Editar Clase Hallazgo</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('clasehallazgo.index') }}"> Regresar</a>
    </div>
  </div>
</div>

@if ($errors->any())
<div class="alert alert-danger">
  <strong>Whoops!</strong> Parece que tenemos algun problema con su Actualizacion.<br><br>
  <ul>
    @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
    @endforeach
  </ul>
</div>
@endif

<form action="{{ route('clasehallazgo.update',$claseh->id) }}" method="POST">
  @csrf
  @method('PUT')

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
      <div class="form-group">
        <strong>Nombre Canal:</strong>
        <input type="text" name="nombre_clase" value="{{ $claseh->nombre_clase }}" class="form-control" placeholder="Nombre Clase">
      </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
  </div>

</form>

@endsection

resources/views/trade/clasehallazgo/index.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2>Trade Clases de Hallazgos</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-success" href="{{ route('clasehallazgo.create') }}"><i class="fas fa-plus-circle"></i> Nueva Clase de Hallazgo</a>
    </div>
  </div>
</div>

@if ($message = Session::get('success'))
  @include('layouts.alert_success')
@endif

<div class="table-responsive-sm">
  <table class="table table-hover table-bordered table-sm">
    <thead>
      <tr>
        <!--<th>Id</th>-->
        <th>Nombre Clase</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($clasesH as $claseh)
      <tr>
        <!--<td>{{ $claseh->id }}</td>-->
        <td>{{ $claseh->nombre_clase }}</td>
        <td>

          <form action="{{ route('clasehallazgo.destroy',$claseh->id) }}" method="POST">
            @csrf
            @method('DELETE')
            <a class="btn btn-sm btn-info" data-toggle="tooltip" data-placement="top" title="Ver Clase" href="{{ route('clasehallazgo.show',$claseh->id) }}">
              <i class="fas fa-search"></i></a>
            <a class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar Clase" href="{{ route('clasehallazgo.edit',$claseh->id) }}"><i class="fas fa-edit"></i></a>

            <button type="submit" data-toggle="tooltip" data-placement="top" title="Borrar Clase" class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i></button>
          </form>
        </td>
      </tr>
    </tbody>
    @endforeach
  </table>
</div>

{!! $clasesH->links() !!}

@endsection

resources/views/trade/clasehallazgo/show.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
  <div class="col-lg-12 margin-tb">
    <div class="pull-left">
      <h2> Ver Clase Hallazgo</h2>
    </div>
    <div class="pull-right">
      <a class="btn btn-sm btn-primary" href="{{ route('clasehallazgo.index') }}"> Regresar</a>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Id:</strong>
      {{ $claseh->id }}
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-12">
    <div class="form-group">
      <strong>Nombre:</strong>
      {{ $claseh->nombre_clase }}
    </div>
  </div>
</div>

@endsection